trigger:
  branches:
    include:
      - main
      - danny

pool:
  vmImage: "ubuntu-latest"

variables:
  node_version: "20.x"

stages:
  - stage: Build
    jobs:
      - job: Backend
        displayName: "Build Backend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: "Install Node.js"

          # Install dependencies for root
          - script: npm install
            displayName: "Install root dependencies"

          # Install dependencies for client
          - script: |
              cd client
              npm install
            displayName: "Install client dependencies"

          # Install dependencies for server
          - script: |
              cd server
              npm install
            displayName: "Install server dependencies"

          # Run build
          - script: npm run build
            displayName: "Build app"

          # Run tests
          - script: npm run test
            displayName: "Run Unit Tests"
