trigger:
  branches:
    include:
      - main
      - danny
      - belinda
      - xiao

pool:
  vmImage: "ubuntu-latest"

variables:
  node_version: "20.x"

stages:
  # ========================
  # Danny's Stage
  # ========================
  - stage: danny
    displayName: "Danny Branch Build"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/danny')
    jobs:
      - job: DannyBackend
        displayName: "Danny - Backend Build"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: "Install Node.js"

          - script: |
              npm install
              npm run build
            displayName: "Install & Build Backend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "backend/dist"
              ArtifactName: "danny-backend"
              publishLocation: "Container"

  # ========================
  # Belinda's Stage
  # ========================
  - stage: belinda
    displayName: "Belinda Branch Build"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/belinda')
    jobs:
      - job: BelindaFrontend
        displayName: "Belinda - Frontend Build"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: "Install Node.js"

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: "Install & Build Frontend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "frontend/dist"
              ArtifactName: "belinda-frontend"
              publishLocation: "Container"

  # ========================
  # Xiao's Stage
  # ========================
  - stage: xiao
    displayName: "Xiao Branch Build"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/xiao')
    jobs:
      - job: XiaoCheck
        displayName: "Xiao - Placeholder Job"
        steps:
          - script: echo "Xiao’s pipeline runs only on xiao branch."
            displayName: "Echo Xiao Job"
