trigger:
  branches:
    include:
      - main
      - vinix-r1

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd client
    npm install
  displayName: 'Install dependencies'

- script: |
    cd client
    npm test -- --watchAll=false --passWithNoTests --testPathPattern=".*\\.test\\.js$"
  displayName: 'Run JavaScript tests only'
  continueOnError: false  