trigger:
  branches:
    include:
      - main
      - vinix-r1

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
- script: cd client && npm install
- script: cd client && npm test -- --watchAll=false --passWithNoTests