trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build application'

- script: |
    npm test -- --watchAll=false --passWithNoTests
  displayName: 'Run tests'
  continueOnError: true  # Pipeline continues even if tests fail