trigger:
  branches:
    include:
      - main # Runs when you push to main
      - danny

pool:
  vmImage: "ubuntu-latest"

variables:
  node_version: "20.x"

stages:
  - stage: Build
    jobs:
      - job: Backend
        displayName: "Build Backend"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: "Install Node.js"

          - script: |
              npm install
              npm run build
            displayName: "Install & Build Backend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "client/dist"
              ArtifactName: "client"
              publishLocation: "Container"

              # testing
