trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVersion: "18.x"

stages:
  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: FrontendTests
        displayName: 'Frontend Tests'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          - script: |
              cd client
              npm install --legacy-peer-deps
            displayName: 'Install Frontend Dependencies'

          - script: |
              cd client
              npm run test
            displayName: 'Run Frontend Tests'

      - job: BackendTests
        displayName: 'Backend Tests'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          - script: |
              cd server
              npm install
            displayName: 'Install Backend Dependencies'

          - script: |
              cd server
              npm run test
            displayName: 'Run Backend Tests'

  - stage: Build
    displayName: 'Build Stage'
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: BuildApplication
        displayName: 'Build Application'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          - script: |
              cd client
              npm install --legacy-peer-deps
              npm run build
            displayName: 'Build Frontend'

          - script: |
              cd server
              npm install
              npm run build
            displayName: 'Build Backend'
