
trigger:
  branches:
    include:
      - main
      - dev


pool:
  vmImage: "ubuntu-latest"


variables:
  nodeVersion: "18.x"


stages:
  
  - stage: Test
    displayName: 'Test Stage'
    jobs:
      
      - job: FrontendTests
        displayName: 'Run Client (Frontend) Tests'
        steps:
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

       
          - script: npm install
            displayName: 'Install client dependencies'
            workingDirectory: 'client' 

        
          - script: npm test
            displayName: 'Run client unit tests'
            workingDirectory: 'client'

      
      - job: BackendTests
        displayName: 'Run Server (Backend) Tests'
        steps:
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

         
          - script: npm install
            displayName: 'Install server dependencies'
            workingDirectory: 'server'
            
         
          - script: npm test
            displayName: 'Run server unit tests'
            workingDirectory: 'server'

 
  - stage: Build
    displayName: 'Build Stage'
    dependsOn: Test 
    jobs:
      
      - job: BuildClient
        displayName: 'Build Client (Frontend)'
        steps:
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          
          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies and build client'
            workingDirectory: 'client'
            
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'client/dist'
              ArtifactName: 'client'
              publishLocation: 'Container'
            displayName: 'Publish client artifact'

     
      - job: BuildServer
        displayName: 'Build Server (Backend)'
        steps:
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          
          - script: npm install
            displayName: 'Install server dependencies'
            workingDirectory: 'server'
            
          
          - script: npx prisma generate
            displayName: 'Run Prisma Generate'
            workingDirectory: 'server'

          
          - script: npm run build
            displayName: 'Build server'
            workingDirectory: 'server'

          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'server' 
              ArtifactName: 'server'
              publishLocation: 'Container'
            displayName: 'Publish server artifact'