trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"

  - script: npm ci
    displayName: Install

  - script: npx prisma generate
    workingDirectory: server
    displayName: Prisma generate

  - script: npx prisma migrate deploy || npx prisma migrate dev -n ci
    workingDirectory: server
    displayName: Prisma migrate

  - script: npm run seed || echo "no seed"
    displayName: Seed

  - script: npm test
    displayName: Test

  - script: npm run build || echo "no build"
    displayName: Build
